Shopping cart
Vitalii-Kazymyrovych/book_store pull request #11
Opened 2024-03-09 10:20 UTC by Vitalii-Kazymyrovych

2024-03-09 14:47 UTC, kerrrusha requested changes

2024-03-09 14:47 UTC, kerrrusha commented on src/main/java/com/project/bookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +                                "Can't find shopping cart by username: " + username));
it should be created if not found

2024-03-10 15:50 UTC, Rommelua requested changes

2024-03-10 15:50 UTC, Rommelua commented on src/main/java/com/project/bookstore/model/CartItem.java
> +    @OneToOne
ManyToOne

2024-03-10 15:50 UTC, Rommelua commented on src/main/java/com/project/bookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +                                "Can't find shopping cart by username: " + username));
not fixed

2024-03-11 10:41 UTC, MentorMA approved these changes

2024-03-11 10:41 UTC, MentorMA commented on src/main/java/com/project/bookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +
```suggestion
```

2024-03-13 11:16 UTC, merged