Implemented order logic. Adjusted all fetch types and created custom …
Vitalii-Kazymyrovych/book_store pull request #12
Opened 2024-03-13 11:19 UTC by Vitalii-Kazymyrovych

…repository methods.

2024-03-13 18:30 UTC, kerrrusha requested changes

2024-03-13 18:30 UTC, kerrrusha commented on src/main/java/com/project/bookstore/model/Order.java
> +public class Order {
dont forget about soft delete approach

2024-03-13 18:30 UTC, kerrrusha commented on src/main/java/com/project/bookstore/model/OrderItem.java
> +public class OrderItem {
dont forget about soft delete approach

2024-03-13 18:30 UTC, kerrrusha commented on src/main/java/com/project/bookstore/model/OrderItem.java
> +@RequiredArgsConstructor
redundant
```suggestion
```

2024-03-13 18:30 UTC, kerrrusha commented on src/main/java/com/project/bookstore/model/Order.java
> +@RequiredArgsConstructor
redundant
```suggestion
```

2024-03-13 18:30 UTC, kerrrusha commented on src/main/java/com/project/bookstore/model/Order.java
> +        }
enum.name().toLowerCase() can be used instead
```suggestion
        NEW,
        PAID,
        PROCESSING,
        DELIVERED,
        CANCELLED
```

2024-03-14 17:25 UTC, olekskov approved these changes

2024-03-17 09:15 UTC, merged