Readme
Vitalii-Kazymyrovych/book_store pull request #15
Opened 2024-05-13 15:44 UTC by Vitalii-Kazymyrovych

2024-05-13 16:31 UTC, kerrrusha requested changes

2024-05-13 16:31 UTC, kerrrusha commented on README.md
> +   - DEBUG_PORT=5005
create .env.sample for that

2024-05-13 16:31 UTC, kerrrusha commented on .env
>  MYSQL_DOCKER_PORT=3306
this file should not be pushed to any open sources. it keeps your secrets. create .env.sample with mock data instead

2024-05-14 06:31 UTC, Elena-Bruyako requested changes
almost perfect!

2024-05-14 06:31 UTC, Elena-Bruyako commented on .env
> -MYSQL_USER=vitalii
rename file to .env.sample according to the previous mentor comment

2024-05-14 06:31 UTC, Elena-Bruyako commented on README.md
> +# Bookstore Spring Boot Project
Also, you can add Database structure (Models and relations)

2024-05-14 08:18 UTC, okuzan approved these changes

2024-05-14 15:00 UTC, merged